apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: postgres:13.16-alpine
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: database-config
                key: POSTGRES_USER
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: database-config
                key: POSTGRES_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: database-config
                key: POSTGRES_PASSWORD
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: database-storage
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: database-pvc