apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: edualb/pucminas-k8s-be:1.0.0
        ports:
          - containerPort: 5000
        env:
          - name: FLASK_DB_TYPE
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: FLASK_DB_TYPE
          - name: FLASK_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: FLASK_DB_HOST
          - name: FLASK_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: FLASK_DB_PORT
          - name: FLASK_DB_USER
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: FLASK_DB_USER
          - name: FLASK_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: FLASK_DB_NAME
          - name: FLASK_DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: backend-config
                key: FLASK_DB_PASSWORD
        resources:
          requests:
            cpu: 200m
          limits:
            cpu: 500m
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1